//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
//using SQLite;
using System;
using System.Data.SQLite;
using System.Net;
using System.Net.Sockets;
using System.Text;

namespace guiDashboard
{
    public class SQLiteDb
    {
        string _path = @"Data Source=C:\Users\Kevin\Desktop\consumption_monitoring.db;Version=3;New=True;Compress=True;";
        public SQLiteDb(string path)
        {
            _path = path;
        }

        public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                //db.CreateTable<Consumption>();
                //db.CreateTable<Track>();
                var command = db.CreateCommand();

                command.CommandText = @"Select * from Track";

                SQLiteDataReader sdr = command.ExecuteReader();

                while (sdr.Read())
                {
                    Console.WriteLine(sdr.GetString(1) + " " + sdr.GetString(2));
                }
                sdr.Close();

                db.Close();

                Console.WriteLine("Hello");
            }
        }
    }


    //public partial class Consumption
    //{
    //    [NotNull]
    //    public Int32 trackid { get; set; }
        
    //    [NotNull]
    //    public String time { get; set; }
        
    //    [NotNull]
    //    public Double consumption { get; set; }
        
    //}
    
    //public partial class Track
    //{
    //    [PrimaryKey, AutoIncrement]
    //    public Int64 id { get; set; }
        
    //    [NotNull]
    //    public String startpoint { get; set; }
        
    //    [NotNull]
    //    public String destination { get; set; }
        
    //    [NotNull]
    //    public Int32 durationinmin { get; set; }
        
    //    [NotNull]
    //    public String trackdate { get; set; }
        
    //    [NotNull]
    //    public String starttime { get; set; }
        
    //    [NotNull]
    //    public String endtime { get; set; }
        
    //}

}
