simulation:SetOutsideTemperature(11.5)
simulation:SetFuelLevelInPercent(0.9)
simulation:AccelerateTo(50)
simulation:HoldSpeedForSeconds(4)
simulation:Turn("left", false)
simulation:SetOutsideTemperature(5.3)
simulation:AccelerateTo(70)
simulation:HoldSpeedForSeconds(3)
simulation:SetFuelLevelInPercent(0.8)
simulation:Turn("right", true)
simulation:AccelerateTo(130)
simulation:HoldSpeedForSeconds(2)
simulation:SetOutsideTemperature(-5.4)
simulation:SetFuelLevelInPercent(0.7)
simulation:AccelerateTo(280)
simulation:HoldSpeedForSeconds(5)
simulation:SetFuelLevelInPercent(0.4)
simulation:SetOutsideTemperature(-10.2)
simulation:AccelerateTo(220)
simulation:HoldSpeedForSeconds(2)
simulation:SetFuelLevelInPercent(0.3)
simulation:AccelerateTo(130)
simulation:HoldSpeedForSeconds(3)